//! Coordinator agent -- cross-repo communication.
//!
//! Manages PR creation, coordination message posting, and dependency
//! tracking via the ForgeAdapter and DependencyGraph.

use crate::coordination::dependency::DependencyGraph;
use crate::coordination::messages;
use crate::types::{
    AgentId, CoordinationMessage, ForgeAdapter, MessageType, PrRef, PrStatus, RepoRef,
};

use super::{CoordinationResult, PatchOutput};

/// The coordinator agent. Handles cross-repo communication and PR lifecycle.
pub struct Coordinator {
    agent_id: AgentId,
    repo: RepoRef,
    base_branch: String,
}

impl Coordinator {
    /// Create a new coordinator for the given agent and repository.
    pub fn new(agent_id: AgentId, repo: RepoRef, base_branch: impl Into<String>) -> Self {
        Self {
            agent_id,
            repo,
            base_branch: base_branch.into(),
        }
    }

    /// Coordinate a patch: create PR, post messages, update dependencies.
    ///
    /// Steps:
    /// 1. Create a PR from the patch output.
    /// 2. Post a coordination message (status report) on the PR.
    /// 3. Check dependency graph for blocked/ready PRs and post updates.
    /// 4. Label the PR for tracking.
    pub fn coordinate(
        &self,
        patch: &PatchOutput,
        forge: &dyn ForgeAdapter,
        deps: &DependencyGraph,
    ) -> anyhow::Result<CoordinationResult> {
        let mut messages_sent: u32 = 0;

        // Derive branch name from the first file touched.
        let branch_name = self.derive_branch_name(patch);

        // Create the PR.
        let pr = forge.create_pr(
            &self.repo,
            &self.pr_title(patch),
            &self.pr_body(patch),
            &branch_name,
            &self.base_branch,
        )?;

        // Label it for but-ai tracking.
        let _ = forge.add_label(&pr, "but-ai");

        // Post a status report coordination message.
        let status_msg = self.status_report_message(patch);
        let rendered = messages::render(&status_msg)?;
        forge.comment(&pr, &rendered)?;
        messages_sent += 1;

        // Check dependencies and post coordination messages for ready PRs.
        let ready_prs = deps.ready();
        for ready_node in &ready_prs {
            if ready_node.pr != pr {
                let dep_msg = self.dependency_status_message(&ready_node.pr, PrStatus::Open);
                let rendered = messages::render(&dep_msg)?;
                let _ = forge.comment(&ready_node.pr, &rendered);
                messages_sent += 1;
            }
        }

        Ok(CoordinationResult {
            pr_created: Some(pr),
            messages_sent,
        })
    }

    /// Post a coordination message to an existing PR.
    pub fn post_message(
        &self,
        forge: &dyn ForgeAdapter,
        pr: &PrRef,
        msg: &CoordinationMessage,
    ) -> anyhow::Result<()> {
        let rendered = messages::render(msg)?;
        forge.comment(pr, &rendered)
    }

    /// Check if all dependencies for a PR are met.
    pub fn dependencies_ready(&self, pr: &PrRef, deps: &DependencyGraph) -> bool {
        deps.dependencies_met(pr)
    }

    fn derive_branch_name(&self, patch: &PatchOutput) -> String {
        let slug = patch
            .files_touched
            .first()
            .map(|f| {
                f.replace('/', "-")
                    .replace(".rs", "")
                    .replace(".ts", "")
                    .chars()
                    .take(40)
                    .collect::<String>()
            })
            .unwrap_or_else(|| "patch".to_string());

        format!("but-ai/{}/{slug}", self.agent_id)
    }

    fn pr_title(&self, patch: &PatchOutput) -> String {
        // Use the first line of the commit message as the PR title.
        patch
            .commit_msg
            .lines()
            .next()
            .unwrap_or("but-ai: automated patch")
            .chars()
            .take(72)
            .collect()
    }

    fn pr_body(&self, patch: &PatchOutput) -> String {
        let files_list: String = patch
            .files_touched
            .iter()
            .map(|f| format!("- `{f}`"))
            .collect::<Vec<_>>()
            .join("\n");

        format!(
            "## Automated Patch\n\n\
             Agent: `{}`\n\
             Tokens used: {}\n\n\
             ### Files Changed\n\
             {files_list}\n\n\
             ---\n\
             *Generated by but-ai*",
            self.agent_id, patch.tokens_used,
        )
    }

    fn status_report_message(&self, patch: &PatchOutput) -> CoordinationMessage {
        CoordinationMessage {
            schema: messages::SCHEMA_VERSION.to_string(),
            message_type: MessageType::StatusReport,
            from: self.agent_id.clone(),
            to: None,
            payload: serde_json::json!({
                "status": "patch_submitted",
                "files_changed": patch.files_touched.len(),
                "tokens_used": patch.tokens_used,
            }),
            timestamp: String::new(),
        }
    }

    fn dependency_status_message(&self, pr: &PrRef, status: PrStatus) -> CoordinationMessage {
        let status_str = match status {
            PrStatus::Open => "open",
            PrStatus::Closed => "closed",
            PrStatus::Merged => "merged",
            PrStatus::Draft => "draft",
        };
        CoordinationMessage {
            schema: messages::SCHEMA_VERSION.to_string(),
            message_type: MessageType::DependencyDeclaration,
            from: self.agent_id.clone(),
            to: None,
            payload: serde_json::json!({
                "pr": pr.to_string(),
                "status": status_str,
                "dependencies_met": true,
            }),
            timestamp: String::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::coordination::dependency::DependencyNode;
    use crate::coordination::forge::InMemoryForge;
    use crate::types::ForgeType;

    fn test_repo() -> RepoRef {
        RepoRef {
            forge: ForgeType::GitHub,
            owner: "test-org".into(),
            repo: "test-repo".into(),
        }
    }

    fn test_coordinator() -> Coordinator {
        Coordinator::new(AgentId("tanaka".into()), test_repo(), "main")
    }

    fn test_patch() -> PatchOutput {
        PatchOutput {
            patch: "diff content".into(),
            commit_msg: "Fix authentication handler\n\nDetails here.".into(),
            files_touched: vec!["src/auth/handler.rs".into()],
            tokens_used: 1500,
        }
    }

    #[test]
    fn coordinate_creates_pr_and_posts_message() {
        let coordinator = test_coordinator();
        let forge = InMemoryForge::new();
        let deps = DependencyGraph::new();
        let patch = test_patch();

        let result = coordinator.coordinate(&patch, &forge, &deps).unwrap();

        assert!(result.pr_created.is_some());
        let pr = result.pr_created.unwrap();
        assert_eq!(pr.number, 1);
        assert!(result.messages_sent >= 1);

        // Verify comment was posted.
        let comments = forge.comments_for(&pr);
        assert!(!comments.is_empty());
        assert!(comments[0].contains("but-ai-message"));
    }

    #[test]
    fn derive_branch_name_from_files() {
        let coordinator = test_coordinator();
        let patch = test_patch();
        let branch = coordinator.derive_branch_name(&patch);
        assert!(branch.starts_with("but-ai/tanaka/"));
        assert!(branch.contains("auth"));
    }

    #[test]
    fn pr_title_truncated() {
        let coordinator = test_coordinator();
        let mut patch = test_patch();
        patch.commit_msg = "A".repeat(100);
        let title = coordinator.pr_title(&patch);
        assert!(title.len() <= 72);
    }

    #[test]
    fn coordinate_with_ready_dependencies() {
        let coordinator = test_coordinator();
        let forge = InMemoryForge::new();
        let mut deps = DependencyGraph::new();

        // Create a pre-existing ready PR.
        let existing_pr = forge
            .create_pr(&test_repo(), "existing", "body", "feat/x", "main")
            .unwrap();
        deps.upsert(DependencyNode {
            pr: existing_pr,
            depends_on: vec![],
            agent: AgentId("other".into()),
            status: PrStatus::Open,
        });

        let patch = test_patch();
        let result = coordinator.coordinate(&patch, &forge, &deps).unwrap();

        // Should have sent message to the ready dependency PR too.
        assert!(result.messages_sent >= 2);
    }
}
